server:
  port: 8080
  host: "0.0.0.0"

consul:
  address: "consul:8500"

service:
  order:
    name: "order-service"
    port: 50051
  inventory:
    name: "inventory-service"
    port: 50052
  payment:
    name: "payment-service"
    port: 50053

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Origin", "Content-Type", "Authorization"]
  expose_headers: ["Content-Type"]
  allow_credentials: true
  max_age: "12h"

jaeger:
  agent_host: "jaeger"
  agent_port: 14268
  service_name: "api-service"

hystrix:
  timeout: 1000
  max_concurrent_requests: 100
  error_percent_threshold: 25
  request_volume_threshold: 10
  sleep_window: 5000

logger:
  service_name: "api-service"
  log_stash_host: "logstash"
  log_stash_port: 5000
  async: true