server:
  port: 8080
  host: "0.0.0.0"

consul:
  address: "consul:8500"

service:
  order:
    name: "order-service"
    port: 50051
  inventory:
    name: "inventory-service"
    port: 50052
  payment:
    name: "payment-service"
    port: 50053

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Origin", "Content-Type", "Authorization"]
  expose_headers: ["Content-Type"]
  allow_credentials: true
  max_age: "12h"

jaeger:
  agent_host: "jaeger"
  agent_port: 14268
  service_name: "api-service"